### ISSUE TITLE
Exceptions on device during install (e.g. no space) are reported incorrectly

### ISSUE THREAD

**Issue by pimterry** [DeviceFarmer/adbkit#366]
After calling `adbClient.install()`, if the install fails due to lack of space, adbkit will fail with:

```javascript
PrematureEOFError: Premature end of stream, needed 1 more bytes
    at Socket.<anonymous> (.../node_modules/@devicefarmer/adbkit/lib/adb/parser.js:119:32)
    at Socket.emit (node:events:539:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  missingBytes: 1
}
```

This is because it's constantly searching for a line containing `SUCCESS` or `FAILURE`, but the actual output is:

```java
Exception occurred while executing 'install':
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:595)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3434)
	at com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShellCommand.java:1446)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1408)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:221)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:5954)
	at android.os.Binder.shellCommand(Binder.java:1049)
	at android.os.Binder.onTransact(Binder.java:877)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:5938)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)
Caused by: java.io.IOException: Requested internal only, but not enough space
	at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:241)
	at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:152)
	at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:167)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:803)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:592)
	... 13 more
```

This is confusing, and makes it seem like it's a protocol error. It would be better if this output was detected properly and the command failed explicitly instead.

I think it would be best to look for 'Exception', parse the start of the text, and throw an error containing the real error message. I think just taking the second line of output would be a reasonable approach to get a useful error message in these cases.

Happy to open a PR to implement this, just let me know if that's something you're open to.

**Comment by koral--** [comment]
Fixed by #403
