### ISSUE TITLE
Push folder | Raw command

### ISSUE THREAD

**Issue by saade** [DeviceFarmer/adbkit#44]
Adb can push folders too, with this library i`m getting EISFOLDER error. I know it uses Stream to push files, but any way to push folders too? 

This library does not have any 'run' method, to send raw commands to adb, something like:

`client.run('pull local/folder /sdcard/folder')`

**Comment by saademotion** [comment]
trying to push each file separately (around 30~40 files) gives me an error `ERR_STREAM_WRITE_AFTER_END`

```
[127.0.0.1:52001] Pushed 4096 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 24576 bytes so far
[127.0.0.1:52001] Pushed 8720 bytes so far
[127.0.0.1:52001] Pushed 24576 bytes so far
[127.0.0.1:52001] Pushed 8720 bytes so far
[127.0.0.1:52001] Pushed 24576 bytes so far
[127.0.0.1:52001] Pushed 8720 bytes so far
[127.0.0.1:52001] Pushed 4096 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 53592 bytes so far
[127.0.0.1:52001] Pushed 36864 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 4096 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 16928 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 8720 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 32768 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 24576 bytes so far
[127.0.0.1:52001] Pushed 8720 bytes so far
[127.0.0.1:52001] Pushed 16384 bytes so far
[127.0.0.1:52001] Pushed 25136 bytes so far
[127.0.0.1:52001] Pushed 1510 bytes so far
[127.0.0.1:52001] Pushed 53 bytes so far
[127.0.0.1:52001] Pushed 158 bytes so far
[127.0.0.1:52001] Pushed 127 bytes so far
[127.0.0.1:52001] Pushed 50842 bytes so far
[127.0.0.1:52001] Pushed 69 bytes so far
[127.0.0.1:52001] Pushed 699 bytes so far
[127.0.0.1:52001] Pushed 1192 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 65536 bytes so far
[127.0.0.1:52001] Pushed 1024 bytes so far
[127.0.0.1:52001] Pushed 1024 bytes so far
[127.0.0.1:52001] Pushed 1024 bytes so far
[127.0.0.1:52001] Pushed 1024 bytes so far
[127.0.0.1:52001] Pushed 1024 bytes so far
[127.0.0.1:52001] Pushed 727 bytes so far
[127.0.0.1:52001] Pushed 11200 bytes so far
[127.0.0.1:52001] Pushed 1591 bytes so far
[127.0.0.1:52001] Pushed 2517 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 8401 bytes so far
[127.0.0.1:52001] Pushed 6115 bytes so far
[127.0.0.1:52001] Pushed 1197 bytes so far
[127.0.0.1:52001] Pushed 139 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 112 bytes so far
[127.0.0.1:52001] Pushed 300 bytes so far
[127.0.0.1:52001] Pushed 514 bytes so far
[127.0.0.1:52001] Pushed 7647 bytes so far
[127.0.0.1:52001] Pushed 226 bytes so far
[127.0.0.1:52001] Pushed 651 bytes so far
[127.0.0.1:52001] Pushed 710 bytes so far
[127.0.0.1:52001] Pushed 364 bytes so far
[127.0.0.1:52001] Pushed 3201 bytes so far
[127.0.0.1:52001] Pushed 145 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 801 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 129 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 65 bytes so far
[127.0.0.1:52001] Pushed 127 bytes so far
[127.0.0.1:52001] Push complete
[127.0.0.1:52001] Push complete
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Connection.write (P:\Projects\adb-interact\node_modules\adbkit\lib\adb\connection.js:70:17)
    at Sync._sendCommandWithLength (P:\Projects\adb-interact\node_modules\adbkit\lib\adb\sync.js:307:28)
    at P:\Projects\adb-interact\node_modules\adbkit\lib\adb\sync.js:160:19
    at tryCatcher (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\promise.js:244:10)
    at Async._drainQueue (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (P:\Projects\adb-interact\node_modules\adbkit\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleError (P:\Projects\adb-interact\node_modules\adbkit\lib\adb\connection.js:99:12)
    at Socket.<anonymous> (P:\Projects\adb-interact\node_modules\adbkit\lib\adb\connection.js:53:22)
    at Socket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by UrielCh** [comment]
no detail to replicate, should be close.

**Comment by saade** [comment]
Nov 15, 2020 😅
