### ISSUE TITLE
adb connect api issue

### ISSUE THREAD

**Issue by slugger941** [DeviceFarmer/adbkit#64]
I want to test adb coonect by wifi.
So i use client.connect api to connect remote device.
But if I set ip that not used by any device, error is occured and main process is stopped.
I think that main process should not be stopped tough error is occured.
Let me know how to handle it.
My test code is like below.

let adb = require('adbkit');
let client = adb.createClient();

client.connect('192.168.0.1', '5555')
.then(function(id) {
console.log('connect id:%s', id);
})
.catch(function(err) {
console.error('Something went wrong:', err.stack);
})

Something went wrong: Error: cannot connect to 192.168.0.1:5555: ?곌껐??援ъ꽦?먯쑝濡쒕????묐떟???놁뼱 ?곌껐?섏? 紐삵뻽嫄곕굹, ?몄뒪?몃줈遺�???묐떟???놁뼱 ?곌껐???딆뼱議뚯뒿?덈떎. (10060)
at C:\code\testapp\node_modules\adbkit\lib\adb\command\host\connect.js:30:23
at tryCatcher (C:\code\testapp\node_modules\bluebird\js\main\util.js:26:23)
at Promise._settlePromiseFromHandler (C:\code\testapp\node_modules\bluebird\js\main\promise.js:503:31)
at Promise._settlePromiseAt (C:\code\testapp\node_modules\bluebird\js\main\promise.js:577:18)
at Async._drainQueue (C:\code\testapp\node_modules\bluebird\js\main\async.js:128:12)
at Async._drainQueues (C:\code\testapp\node_modules\bluebird\js\main\async.js:133:10)
at Immediate.Async.drainQueues [as _onImmediate] (C:\code\testapp\node_modules\bluebird\js\main\async.js:15:14)

**Comment by koral--** [comment]
Could you translate that Korean error message to English?

**Comment by slugger941** [comment]
Something went wrong: Error: failed to connect to '192.168.0.1:5555': Connection refused

**Comment by slugger941** [comment]
.search-word {
	BACKGROUND-COLOR: #ffee94
}
P {
	FONT-SIZE: 10pt; MARGIN-BOTTOM: 5px; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
TD {
	FONT-SIZE: 10pt; MARGIN-BOTTOM: 5px; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
LI {
	FONT-SIZE: 10pt; MARGIN-BOTTOM: 5px; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}
BODY {
	FONT-SIZE: 10pt; FONT-FAMILY: 맑은 고딕, arial; MARGIN: 10px; LINE-HEIGHT: 1.4
}


P {
	FONT-SIZE: 10pt; MARGIN-BOTTOM: 5px; FONT-FAMILY: 맑은 고딕, arial; MARGIN-TOP: 5px
}





Something went wrong: Error: failed to connect to '192.168.0.1:5555': Connection refused
 
I also commented.
Thanks
 
--------- Original Message ---------
Sender : Karol Wrótniak <notifications@github.com>
Date : 2021-01-05 04:43 (GMT+9)
Title : Re: [DeviceFarmer/adbkit] adb connect api issue (#64)
 

Could you translate that Korean error message to English?

**Comment by slugger941** [comment]
is this issue resolved??

**Comment by koral--** [comment]
Not yet. Status is not changed.

**Comment by drauggres** [comment]
I can't reproduce it with `@devicefarmer/adbkit@2`

```javascript

let adb = require("@devicefarmer/adbkit");
let client = adb.createClient();

client.connect("127.0.0.1", "5555").then(function(id) {
  console.log("connect id:%s", id);
}).catch(function(err) {
  console.error("Something went wrong:", err.stack);
});

setInterval(() => {
  console.log('ping')
}, 1000);
```
Output:
```
Something went wrong: Error: failed to connect to '127.0.0.1:5555': Connection refused
    at /tmp/test/node_modules/@devicefarmer/adbkit/lib/adb/command/host/connect.js:30:23
    at tryCatcher (/tmp/test/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/tmp/test/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/tmp/test/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/tmp/test/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/tmp/test/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/tmp/test/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
ping
ping
ping
```

The main process continues to run. Tested on node 10, 12, 14, 16, 17

**Comment by trueicecold** [comment]
A bit late to the party but just wrap it with try/catch:

`
try {
        await adbClient.connect('1.2.3.4', 5555);
        await adbClient.waitForDevice();
        return {
            status: 1
        }
    }
    catch (e) {
        return {
            status: 0,
            error: e.message
        };
    }
`
