### ISSUE TITLE
client.waitForDevice(serial) not working

### ISSUE THREAD

**Issue by timansky** [DeviceFarmer/adbkit#80]
Method is not working anymore

```
Unhandled rejection FailError: Failure: 'short wait-for-: any'
    at /tools/node_modules/@devicefarmer/adbkit/lib/adb/parser.js:183:29
    at tryCatcher (/tools/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/tools/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/tools/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/tools/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/tools/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/tools/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

adb server used to accept the command 'wait-for-any', but now the command has to be 'wait-for-any-device'.

**Comment by drauggres** [comment]
This could be closed, since the fix has been merged.

@timansky FYI next time you can use [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link commits/PR with an issue (i.e. issue will be closed automatically after commit with keyword is merged)
