### ISSUE TITLE
Problem pulling files when running inside a Docker container since upgrading to 3.2.0

### ISSUE THREAD

**Issue by soulgalore** [DeviceFarmer/adbkit#94]
Hi and thanks for the great tool, I've been using it for a long time in https://github.com/sitespeedio/browsertime.

A couple of days ago I upgraded from 2.11.3 to 3.2.0. It's been working great but I've run into problem when I run the code in Docker and I cannot understand why. Running it on Big Sur and Ubuntu works fine, but when I run it in a Docker container it fails when I try to pull a file.

The error I get is:
```
ERROR: TypeError: Cannot read property 'length' of null
    at tryRead (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:178:42)
    at bluebird_1.default (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:202:13)
    at Promise.cancellationExecute [as _execute] (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/debuggability.js:406:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:103:10)
    at Parser.readByteFlow (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/parser.js:171:16)
    at parser.readBytes.then (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/dist/src/adb/sync.js:250:48)
    at tryCatcher (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/sitespeed.io/node_modules/@devicefarmer/adbkit/node_modules/bluebird/js/release/async.js:15:14)
```

And the code on Browsertime side is:
https://github.com/sitespeedio/browsertime/blob/main/lib/android/index.js#L86-L98

Using 2.11.3 works fine so it happens after the upgrade. I'm not sure if I missed something on my side or if its a bug. What's the best way to debug it on my side?

**Comment by koral--** [comment]
Version 3.2.0 is broken unfortunately. 
Here is the reason: https://github.com/DeviceFarmer/adbkit/issues/85#issuecomment-792700463
Not sure yet how to deal with that.
If time permits or @urielCh provides some help we will fix that. Otherwise maybe we revert some changes.

**Comment by soulgalore** [comment]
Ok cool, I'll revert then.

**Comment by UrielCh** [comment]
Hi,
I'm back to android ADB developpement.

May I help 😃

**Comment by UrielCh** [comment]
a new major version are available [@u4/adbkit](https://www.npmjs.com/package/@u4/adbkit)
